config/routes.rb
Rails.application.routes.draw do

  patch 'customers' => 'public/customers#update'
  get 'orders/thanks' => 'public/orders#thanks'

  root to: 'public/homes#top'
   get'about' => 'public/homes#about'
   get 'customers/edit' => 'public/customers#edit'
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    resources :homes, only:[:about]
    resources :items, only:[:index,:show]
    resources :carts, only:[:index, :update, :destroy, :create]
    resources :orders, only:[:new, :confirm, :thanks, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/bye' => 'customers#bye'
    patch 'customers/adios' => 'customers#adios'
    post 'orders/confirm' => 'orders#confirm'
    delete 'carts' => 'carts#all', as: 'all'
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :update, :edit]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer=Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :lastname_kana, :first_kana, :email, :postal_code, :address, :phone_number, :is_deleted )
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <h4 style="margin-top:30px;"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
   <%= form_with model: @customer, url: admin_customer_path(@customer.id), class: "w-100" do |f| %>
 <table>
   <tr>
     <td>会員ID</td>
     <td class= "col-sm-8"><%= @customer.id %></td>
   </tr>
   <tr>
     <td>氏名</td>
     <td><%= f.text_field :first_name %> <%= f.text_field :last_name %></td>
   </tr>
   <tr>
     <td>フリガナ</td>
     <td><%= f.text_field :first_name_kana %> <%= f.text_field :last_name_kana %></td>
   </tr>
   <tr>
     <td>郵便番号</td>
     <td><%= f.text_field :postal_code %></td>
   </tr>
   <tr>
     <td>住所</td>
     <td><%= f.text_field :address %></td>
   </tr>
   <tr>
     <td>電話番号</td>
     <td><%= f.text_field :phone_number %></td>
   </tr>
   <tr>
     <td>メールアドレス</td>
     <td><%= f.text_field :email %></td>
   </tr>
   <tr>
     <td>会員ステータス</td>
     <td>
        <%= f.radio_button :is_deleted, :false, class:"col-sm-1" %>
        <%= f.label :is_deleted, "有効", value: false %>
        <%= f.radio_button :is_deleted, :true, class:"col-sm-1"%>
        <%= f.label :is_deleted, "退会", value: true %>
     </td>
    </tr>
 </table>
     <%= f.submit "変更を保存" , class:"btn btn-success btn-sm", style:"margin-left:200px"%>
 <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
<h4 style="margin-top:30px;">会員一覧</h4>

 <table class="table">
   <thead>
     <tr class="table-active">
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
     </tr>
   </thead>
 
  <% @customers.each do |customer| %>
  <tr>
    <tbody>
      <td><%= customer.id %></td>
      <td>
        <%= link_to admin_customer_path(customer.id) do %>
          <%= customer.first_name %><%= customer.last_name %>
          <% end %>
      </td>
      <td><%= customer.email %></td>
      <% if customer.is_deleted == false %>
        <td class="text-success">有効</td>
      <% else %>
        <td>退会</td>
      <% end %>
    </tbody>
  </tr>
  <% end %>
</table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
<h4 style="margin-top:30px;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>

<table class="table.table-borderless.table-sm">
  <tr>
    <td>会員ID</td>
    <td class="col-sm-6"><%= @customer.id %></td>
  </tr>
  <tr>
    <td>氏名</td>
    <td class="col-sm-6"><%= @customer.last_name %> <%= @customer.first_name %></td>
  </tr>
  <tr>
    <td>フリガナ</td>
    <td class="col-sm-6"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td class="col-sm-6"><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td class="col-sm-6"><%= @customer.address %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td class="col-sm-6"><%= @customer.phone_number %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td class="col-sm-6"><%= @customer.email %></td>
  </tr>
  <tr>
    <td>会員ステータス</td>
      <% if @customer.is_deleted==false %>
    <td class="col-sm-6">有効</td>
      <% else %>
    <td class="col-sm-6">退会</td>
      <% end %>
  </tr>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success btn-sm col-sm-2", style:"margin-top:30px;" %>
<%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary btn-sm col-sm-2", style:"margin-top:30px;"%>
</div>