config/routes.rb
Rails.application.routes.draw do

  patch 'customers' => 'public/customers#update'
  get 'orders/thanks' => 'public/orders#thanks'

  root to: 'public/homes#top'
   get'about' => 'public/homes#about'
   get 'customers/edit' => 'public/customers#edit'
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    resources :homes, only:[:about]
    resources :items, only:[:index,:show]
    resources :carts, only:[:index, :update, :destroy, :create]
    resources :orders, only:[:new, :confirm, :thanks, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/bye' => 'customers#bye'
    patch 'customers/adios' => 'customers#adios'
    post 'orders/confirm' => 'orders#confirm'
    delete 'carts' => 'carts#all', as: 'all'
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :update, :edit]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, prepare: 3, done: 4 }

   belongs_to :customer
   has_many :order_details, dependent: :destroy

  def total_amount
    sum=0
    order_details.each do |order_detail|
      sum+=order_detail.amount
    end
    return sum
  end

  def item_total_price
    sum=0
    order_details.each do |order_detail|
      sum+=order_detail.subtotal
    end
    return sum
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!

  def index
  		@orders = Order.all.page(params[:page]).per(10)
  end

  def current_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render :index
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render :index
  end

	def show
		@order = Order.find(params[:id])
		@total=0
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
		   flash[:success] = "注文ステータスを変更しました"
		   redirect_to admin_order_path(@order)
		else
		   render "show"
		end
	end

	private
	def order_params
		  params.require(:order).permit(:status)
	end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide(:title, "注文履歴一覧") %>
<h2 class="head-line title_h2 text-center">注文履歴一覧</h2>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<table class="table table-hover table-bordered table-condensed">
		  <thead>
		    <tr class="info">
		      <th class="col-xs-3"><i class="far fa-clock"></i>購入日時</th>
	      	  <th><i class="far fa-user"></i>購入者</th>
		      <th class="col-xs-1">注文個数</th>
		      <th class="col-xs-2">注文ステータス</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @orders.each do |order| %>
		      <tr>
		        <td>
		          <%= link_to admin_order_path(order), data: {"turbolinks" => false}, :style=>"color:#528fff;"  do %>
		          	<%= order.created_at %>
		          <% end %>
		        </td>
		        <td class="text-left">
		          <%= full_name(order.customer) %>
		        </td>
		        <td class="text-right">
		          <%= order.order_details.count %>
		        </td>
    	        <td>
    	      	  <%= order.making_status %>
     	        </td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
    <div class="text-center"><%= paginate(@orders) %></div>
</div>

app/views/admin/orders/show.html.erb
<div class="container-fluid p-5">
  <div class="row h5 pb-4">
    <div class="text-center col-auto bg-light offset-sm-2 h-25">注文履歴詳細</div>
  </div>
  <div class="row">
    <table class="table table-borderless col-sm-7 offset-sm-1">
      <tr>
        <th style="width:25%">購入者</th>
        <td style="width:75%">
          <%# <%= link_to admin_orders_path do %>
          <%= @order.customer.last_name %><%= @order.customer.first_name %>
          <%# end %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %> <%= @order.address %><br>
          <%= @order.receiver_name %>
        </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <th class="align-middle">注文ステータス</th>
        <td>
          <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
            <%= f.select :status, Order.statuses_i18n.invert,{} %><%= f.submit "更新", class: "btn btn-success ml-5" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row mt-3">
    <table class="table col-sm-9">
      <tr>
        <thead class="thead-light">
          <th style="width:30%">商品名</th>
          <th class="text-center" style="width:20%">単価（税込）</th>
          <th class="text-center" style="width:10%">数量</th>
          <th class="text-center" style="width:12%">小計</th>
          <th style="width:28%">製作ステータス</th>
        </thead>
      </tr>
      <% @order.order_details.each do |order_detail| %>
      <tr>
        <tbody>
          <td class="align-middle"><%= order_detail.item.name %></td>
          <td class="text-center align-middle"><%= order_detail.item.with_tax_price.to_s(:delimited) %></td>
          <td class="text-center align-middle"><%= order_detail.amount %></td>
          <td class="text-center align-middle"><%= order_detail.subtotal.to_s(:delimited) %></td>
          <td class="align-middle px-o">
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
              <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {} %>
              <%= f.submit "更新", class: "btn btn-success btn-sm ml-3" %>
            <% end %>
          </td>
        </tbody>
      </tr>
      <% @total+=order_detail.subtotal %>
      <% end %>
    </table>
    <table class="table table-borderless col-sm-3 mt-auto table-sm">
      <tr>
        <th>商品合計</th>
        <td><%= @total.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @order.postage.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th>請求金額</th>
        <td><%= @order.billing_amount.to_s(:delimited, delimiter: ',') %>円</td>
        
      </tr>
    </table>