config/routes.rb
Rails.application.routes.draw do

  patch 'customers' => 'public/customers#update'
  get 'orders/thanks' => 'public/orders#thanks'

  root to: 'public/homes#top'
   get'about' => 'public/homes#about'
   get 'customers/edit' => 'public/customers#edit'
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    resources :homes, only:[:about]
    resources :items, only:[:index,:show]
    resources :carts, only:[:index, :update, :destroy, :create]
    resources :orders, only:[:new, :confirm, :thanks, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/bye' => 'customers#bye'
    patch 'customers/adios' => 'customers#adios'
    post 'orders/confirm' => 'orders#confirm'
    delete 'carts' => 'carts#all', as: 'all'
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :update, :edit]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!, except: [:show]

  def index
    @genre = Genre.new
    @genres = Genre.all.page(params[:page]).per(10)
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all.page(params[:page]).per(10)
    if @genre.save
       flash[:notice] = "ジャンルを追加しました"
       redirect_to admin_genres_path
    else
       flash[:notice] = "ジャンルを追加できませんでした"
       render :index 
    end
  end

  def show
    @items = Item.all.all.page(params[:page]).per(10)
    @genre = Genre.find(params[:id])
    @genres = @genre.items.order(created_at: :desc).all.page(params[:page]).per(5)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:success] = "ジャンルを変更しました"
      redirect_to admin_genres_path
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="col-xs-12 ">
<% provide(:title, "ジャンル編集") %>
<h2 class="head-line title_h2 text-center bg-">ジャンル編集</h2>

<% if @genre.errors.any? %>
<%= render "layouts/error_messages", resource: @genre %>
<% end %>

<%= form_with model: [:admin, @genre], local:true do |f| %>
<div class="col-xs-8 col-xs-offset-2">
  <table class="table table-hover table-inverse table-bordered">
     <tr>
<td>ジャンル名</td>
<td><%= f.text_field :name %></td>
<td><%= f.submit "変更を保存", class: "glyphicon glyphicon-home btn btn-success" %></td>
     </tr>
<% end %>
 </table>
</div>
<div class="col-xs-12">
  <%= link_to "戻る", admin_genres_path, class: "glyphicon glyphicon-home btn btn-info" %>
</div>
 </div>
  </div>

app/views/admin/genres/index.html.erb
<% provide(:title, "ジャンル一覧・追加") %>
<div class="row">
  <div class="col-xs-11">
    <h4><%= flash[:notice] %></h4>
    <h2 class="head-line title_h2 text-center">ジャンル一覧・追加</h2>
      <%= form_for @genre, :url => {:action => :create} do |f| %>
        <div class="col-xs-offset-1">
          <i class="fas fa-candy-cane"></i>ジャンル
          <%= f.text_field :name  %>
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      <% end %>
    <div class="col-xs-8 col-xs-offset-2">
      <table class="table table-hover table-inverse table-bordered">
        <thead>
          <tr class="info">
            <th>ジャンル</th>
            <th>状態</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td class="text-left"><%= genre.name%></td>

              <td class="genre-td"><%= link_to "編集する", edit_admin_genre_path(genre), class: "glyphicon glyphicon-pencil btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
    <div class= "text-center"><%= paginate(@genres) %></div>
</div>

app/views/admin/genres/show.html.erb
<% provide(:title, "#{@genre.name}一覧") %>
<h2 class="product-headlinehead-line title_h2 text-center"><%= @genre.name %>一覧</h2>
</span>
<div class="row">
  <div class="col-xs-3 product-index">
    <%= render "layouts/genre_search", items: @items %>
  </div>
  <div class="col-xs-9 product-index">
      <div class="clearfix product-box">
        <% @genres.first(6).each do |item| %>
          <%= render "customer/items/item_each", item: item %>
        <% end %>
      </div>
     <div class="text-center"><%= paginate(@genres) %></div>
  </div>
 
</div>