config/routes.rb
Rails.application.routes.draw do

  patch 'customers' => 'public/customers#update'
  get 'orders/thanks' => 'public/orders#thanks'

  root to: 'public/homes#top'
   get'about' => 'public/homes#about'
   get 'customers/edit' => 'public/customers#edit'
   devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  scope module: :public do
    resources :homes, only:[:about]
    resources :items, only:[:index,:show]
    resources :carts, only:[:index, :update, :destroy, :create]
    resources :orders, only:[:new, :confirm, :thanks, :create, :index, :show]
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    get 'customers/my_page' => 'customers#show'
    get 'customers/edit' => 'customers#edit'
    get 'customers/bye' => 'customers#bye'
    patch 'customers/adios' => 'customers#adios'
    post 'orders/confirm' => 'orders#confirm'
    delete 'carts' => 'carts#all', as: 'all'
  end

  namespace :admin do
    root :to => 'homes#top'
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :update, :edit]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :postel_code, presence: true
  validates :address, presence: true
  validates :receiver_name, presence: true
  
  def address_info
    "〒" + self.postel_code + " " + self.address + "　" + self.receiver_name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
   belongs_to :customer
   belongs_to :item

   def subtotal
    item.with_tax_price * count
   end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :carts, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  
  validates :name, presence: true
  validates :description, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
  validates :image, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, prepare: 3, done: 4 }

   belongs_to :customer
   has_many :order_details, dependent: :destroy

  def total_amount
    sum=0
    order_details.each do |order_detail|
      sum+=order_detail.amount
    end
    return sum
  end

  def item_total_price
    sum=0
    order_details.each do |order_detail|
      sum+=order_detail.subtotal
    end
    return sum
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { impossible: 0, waiting: 1, making: 2, done: 3 }
  belongs_to :item
  belongs_to :order

  def subtotal
    item.with_tax_price * amount
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.new
    @orders = Order.all.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page])
  end

  def new
    @item = Item.new
  end
  
   def create
    @item = Item.new(item_params)
    if @item.save
     flash[:notice] = "新規登録に成功しました"
     redirect_to admin_item_path(@item.id)
    else
     flash[:notice] = "新規登録に失敗しました"
     render new_admin_item_path
    end
   end
   
   def update
       item = Item.find(params[:id])
       item.update(item_params)
       redirect_to admin_item_path(item)
   end

  def show
      @item = Item.find(params[:id])
  end

  def edit
      @item = Item.find(params[:id])
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :image, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_admin_sign_in_path_for(resource)
    admin_root_path
  end
  
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      customers_my_page_path
    end
  end


  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>© All rights reserved by Webnopu-.</p>
        <%= link_to "管理者の方はこちら", "/admin/sign_in" %>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom">
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <div class="container-fluid mx-5">
          <span class="navbar-brand mb-0 h-1">
      <% if admin_signed_in? %>
      <%= link_to "NaganoCAKE", admin_root_path, class: "btn btn-warning" %>
      <% else %>
      <%= link_to "NaganoCAKE", root_path, class: "btn btn-warning" %>
      <% end %>
    </span>
        <% if customer_signed_in? %>
         <!--カスタマーがログインしている時 -->
          <span class="navbar-text-dark mx-auto">
            ようこそ、<%= current_customer.first_name + current_customer.last_name %>さん！
          </span>
          <% end %>
          
          <div class="d-flex flex-column ml-auto">
          <div class="row ml-auto">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
          <li class="nav-item m-3">
            <%= link_to "マイページ", customers_my_page_path(current_customer), class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "商品一覧", items_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to carts_path, data: {"turbolinks" => false},
             class: "nav-link text-dark btn btn-warning" do %>カート(<%= current_customer.carts.count %>個)
            <% end %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "nav-link text-dark btn btn-warning" %>
          </li>

        <% elsif admin_signed_in? %>

          <!-- 管理者がログインしている時 -->
          <li class="nav-item m-3">
            <%= link_to "商品一覧", admin_items_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "会員一覧", admin_customers_path, class: "nav-link text-dark btn btn-warning"  %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link text-dark btn btn-warning" %>
          </li>
        <% else %>
           <li class="nav-item m-3">
            <%= link_to "About", about_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "商品一覧", items_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "新規登録", new_customer_registration_path, data: {"turbolinks" => false}, class: "nav-link text-dark btn btn-warning" %>
          </li>
          <li class="nav-item m-3">
            <%= link_to "ログイン", new_customer_session_path, class: "nav-link text-dark btn btn-warning" %>
          </li>
        <% end %>
      </ul>
            </div>
          </div>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body id="wrapper">
    <div id="header">
      <%= render "layouts/header" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>